name: Build and push Docker image

on:
  push:
    tags:
    - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Check docker image name and version
        run: echo "$GITHUB_REPOSITORY:$GITHUB_REF_NAME"

      - name: Build the image
        run: docker build -t $GITHUB_REPOSITORY:$GITHUB_REF_NAME .

      - name: Check images
        run: docker images | grep $GITHUB_REF_NAME

      - name: Login in docker
        run: docker login -u zeph1rrinc -p ${{secrets.DOCKER_HUB_PASS}}

      - name: Push into registry
        run: |
          docker push $GITHUB_REPOSITORY:$GITHUB_REF_NAME

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          name: "${{ $GITHUB_REPOSITORY }}:${{ GITHUB_REF_NAME }}"
